### PR TITLE
Allow newest IntervalSets

### PR DESCRIPTION
**Pull request by SimonDanisch**

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Would be nice to merge + tag this :)

**Comment by mcabbott** [comment]
Done. Not sure why CompatHelper didn't pick this up, BTW. Maybe it's an old version or something?

**Comment by SimonDanisch** [comment]
Thanks! Maybe github disabled the runner? They did that with my packages, if the package isn't as active.
You can check in the `Actions` tab to see what's going on

**Comment by mcabbott** [comment]
I think it does run, but gives errors: 

https://github.com/mcabbott/AxisKeys.jl/runs/6729826949?check_suite_focus=true

Not sure that's public, but the error is like so:

Screenshot 2022-06-03 at 13 24 32

Haven't got around to investigating further.

**Pull request merged**
